on: [push]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up secret file
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      run: |
        echo $FIREBASE_SERVICE_ACCOUNT >> secrets.txt

    - name: Run tmate
      uses: mxschmitt/action-tmate@v2
