name: Develop CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js and install dependencies
      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          yarn-version: '1.x'
          
          
      - name: Install Dependencies
        run: yarn install

      # Test the code
      - name: Run tests
        run: yarn test

