name: Develop CI/CD

on:
  push:
    branches:
      - develop

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js and install dependencies
      - name: Setup Node.js and install dependencies
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - run: npm ci

      # Test the code
      - name: Run tests
        run: npm test
